### ISSUE TITLE
CN4 issue

### ISSUE THREAD

**Issue by tobigithub** [gilleain/moleculegen#4]
Hi,
java -server -Xms500M -Xmx512M -cp AMG20121014.jar app.AMG -e CN4 -O SMI
N1=NN=2=NC1=2
N1=NC12(N=N2)
N1=N2N3=NC123
N1=NC12(N#N2)
N1=N2=N3=NC123
N#NC=1N#N=1
N1#NN=2=NC1=2
N1#NC12(N#N2)
N1=C2N3N1N23
N1=C2N=3N1N2=3
N1=C2N3N1=N23
N1=C2N=3N1=N2=3
N=1C=2N3N=1N=23
N=1C=2N=3N=1N=2=3
N=1C=2N3N=1=N=23
Exception in thread "main" java.lang.NumberFormatException: For input string: "23700-1"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at org.openscience.cdk.graph.invariant.CanonicalLabeler.createInvarLabel(CanonicalLabeler.java:145)
        at org.openscience.cdk.graph.invariant.CanonicalLabeler.canonLabel(CanonicalLabeler.java:86)
        at org.openscience.cdk.smiles.SmilesGenerator.createSMILESWithoutCheckForMultipleMolecules(SmilesGenerator.java:3
        at org.openscience.cdk.smiles.SmilesGenerator.createSMILES(SmilesGenerator.java:337)
        at org.openscience.cdk.smiles.SmilesGenerator.createSMILES(SmilesGenerator.java:206)
        at handler.PrintStreamStringHandler.getStringForm(Unknown Source)
        at handler.PrintStreamStringHandler.handle(Unknown Source)
        at generate.AtomAugmentingGenerator.extend(Unknown Source)
        at generate.AtomAugmentingGenerator.extend(Unknown Source)
        at generate.AtomAugmentingGenerator.extend(Unknown Source)
        at generate.AtomAugmentingGenerator.extend(Unknown Source)
        at app.AMG.run(Unknown Source)
        at app.AMG.main(Unknown Source)
------------------------------------
Also for SDF output, a bunch of CN4H are generated.
Tobias

**Comment by gilleain** [comment]
Now get 356:

java -jar build/libs/moleculegen-full.jar  -e "C7H2" 
356 structures

**Comment by gilleain** [comment]
Bother. Wrong one.

**Comment by gilleain** [comment]
In any case, this error no longer happens - get 6 structures for both method.
